validator/validator/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('vaxvalidator.urls')),
    path('admin/', admin.site.urls),
]

validator/vaxvalidator/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # path('', views.HomeView.as_view(), name='index'),
    path('', views.LookupLotView.as_view(), name='lot_lookup'),
    path('results/<str:vaccine_brand>/<str:dose_1_lot>/',
         views.ResultsView.as_view(), name='results'),
    path('results/<str:vaccine_brand>/<str:dose_1_lot>/<str:dose_2_lot>',
         views.ResultsView.as_view(), name='results'),
    path('privacy-policy', views.PrivacyPolicyView.as_view(), name='privacy-policy'),
]

validator/vaxvalidator/models.py
from django.db import models


class VaccineAbstract(models.Model):
    lot_num = models.CharField(max_length=32, unique=True)
    expiration_date = models.DateField()
    country_code = models.CharField(max_length=3)
    previous_expiration_date = models.TextField(blank=True)


class ModernaVaccine(VaccineAbstract):
    @property
    def sytem_name(self):
        return f"Moderna: LOT# {self.lot_num}"

    def __str__(self):
        return self.sytem_name


class JanssenVaccine(VaccineAbstract):
    product_name = models.CharField(max_length=32)
    last_updated_on = models.DateTimeField()
    material = models.CharField(max_length=32)
    sku_description = models.TextField()
    batch_status = models.CharField(max_length=32)
    unrestricted = models.CharField(max_length=32)
    restricted = models.CharField(max_length=32)
    quality_inspection = models.CharField(max_length=32)
    z_enterprise_material_number = models.CharField(max_length=32)
    is_negative_temp = models.BooleanField()
    time_stamp = models.DateTimeField()

    @property
    def sytem_name(self):
        return f"J&J: LOT# {self.lot_num}"

    def __str__(self):
        return self.sytem_name

validator/vaxvalidator/forms.py
import requests
from django import forms
from django.conf import settings
from django.core.exceptions import ValidationError

from vaxvalidator.models import ModernaVaccine, JanssenVaccine
from vaxvalidator.utils import get_and_create_jnj


class LotLookUpForm(forms.Form):
    VACCINE_CHOICES = [
        ('moderna', 'Moderna'),
        ('janssen', 'J&J/Janssen'),
    ]
    vaccine_brand = forms.CharField(
        label='Vaccine Brand', widget=forms.Select(choices=VACCINE_CHOICES)
    )
    lot_num_1 = forms.CharField(label='First Dose LOT#')
    lot_num_2 = forms.CharField(label='Second Dose LOT#', required=False)

    def clean(self):
        cleaned_data = super().clean()
        lot_num_1 = cleaned_data.get("lot_num_1")
        lot_num_2 = cleaned_data.get("lot_num_2")
        h_resp = self.data.get("h-captcha-response", "")

        if not h_resp:
            raise ValidationError(
                "Please complete the CAPTCHA!!"
            )

        query_dict = {
            "response": h_resp,
            "secret": settings.HSECRET_KEY
        }
        h_req = requests.get(
            "https://hcaptcha.com/siteverify",
            params=query_dict,
        )
        if not h_req:
            raise ValidationError(
                "Captcha server couldn't be reached."
            )

        if not h_req.json().get("success"):
            raise ValidationError(
                h_req.json().get("error-codes")
            )

    def clean_lot_num_1(self):
        lot_num_1 = self.cleaned_data['lot_num_1']
        return lot_num_1.upper()

    def clean_lot_num_2(self):
        lot_num_2 = self.cleaned_data['lot_num_2']
        return lot_num_2.upper()

validator/vaxvalidator/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.http import HttpResponse
from django.conf import settings
from django.views.generic import TemplateView, FormView


from .forms import LotLookUpForm
from vaxvalidator.models import ModernaVaccine, JanssenVaccine
from vaxvalidator.utils import get_and_create_jnj


class PrivacyPolicyView(TemplateView):
    template_name = "privacy-policy.html"


class ResultsView(TemplateView):
    template_name = "results.html"

    def get_context_data(self, **kwargs):
        context = super(ResultsView, self).get_context_data(**kwargs)
        clean_path = self.request.path.strip("/").split("/")
        context["vaccine_brand"] = clean_path[1]
        context["lot_num_1"] = clean_path[2]
        if len(clean_path) > 3:
            context["lot_num_2"] = clean_path[3]
        return context

    def get(self, request, *args, **kwargs):
        context = self.get_context_data()
        context["lot_num_1_result"] = self.fetch_lot_data(
            context["vaccine_brand"], context["lot_num_1"]
        )
        if context.get("lot_num_2"):
            context["lot_num_2_result"] = self.fetch_lot_data(
                context["vaccine_brand"], context["lot_num_2"]
            )
        return render(request, self.template_name, context=context)

    def fetch_lot_data(self, vaccine_brand, lot_num):
        if vaccine_brand == "moderna":
            result = self.validate_moderna(lot_num)
        elif vaccine_brand == "janssen":
            result = self.validate_janssen(lot_num)
        return result

    def validate_moderna(self, lot_num):
        """
        Moderna is always stored locally so we can retrieve it from the db.
        """
        return ModernaVaccine.objects.filter(lot_num=lot_num).exists()

    def validate_janssen(self, lot_num):
        janssen_vax = JanssenVaccine.objects.filter(lot_num=lot_num).exists()
        if janssen_vax:
            return True
        if not janssen_vax:
            janssen_vax, created = get_and_create_jnj(lot_num)
            if created:
                return True
        return False


class LookupLotView(FormView):
    template_name = 'lot_lookup_form.html'
    form_class = LotLookUpForm
    success_url = '/results'

    def get_context_data(self, **kwargs):
        context = super(LookupLotView, self).get_context_data(**kwargs)
        context["hcaptcha_key"] = settings.HCAPTCHA_SITEKEY
        return context

    def form_valid(self, form):
        # return super().form_valid(form)
        vaccine_brand = form.cleaned_data.get("vaccine_brand")
        lot_num_1 = form.cleaned_data.get("lot_num_1")
        lot_num_2 = form.cleaned_data.get("lot_num_2", "")
        return redirect(f"results/{vaccine_brand}/{lot_num_1}/{lot_num_2}")

validator/vaxvalidator/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" type="text/css" href="{% static 'vaxvalidator/main.css' %}">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    {% block external_js %}
    {% endblock external_js %}
    <title>{% block title %}Vax Card Validator{% endblock title %}</title>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-md navbar-dark fixed-top vax-nav">
        <div class="container-fluid">
          <img src="{% static 'vaxvalidator/images/covid-icon-white.svg' %}" class="me-3" alt="Bootstrap" width="38" height="30">
          <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="navbar-collapse collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/">Home</a>
              </li>
              <!-- <li class="nav-item">
                <a class="nav-link" href="/about">About</a>
              </li> -->
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
      {% block content %}{% endblock content %}
    </main>
    <footer class="text-muted py-5 vax-footer">
      <div class="container">
        <div class="row gx-2 sm-align-center">
          <div class="col-lg-12 col-sm-12">
            <p class="mb-1"><a href="/privacy-policy">Privacy Policy</a></p>
            <p class="mb-1">Developed By: CMHedrick</p>
            <p class="mb-0">Happy Hacking!</p>              
          </div>
        </div>
      </div>
    </footer>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
    -->
  </body>
</html>

validator/vaxvalidator/templates/lot_lookup_form.html
{% extends "base.html" %}

{% block title %}Vax Card Validator | LOT Lookup{% endblock title %}

{% block external_js %}
<script src="https://hcaptcha.com/1/api.js?hl=en" async defer></script>
{% endblock external_js %}

{% block content %}
<section class="py-5 container-fluid virus-bg">
  <form class="container" action="/" method="post">
    <div class="row text-center">
      {% csrf_token %}
      <div class="col-12">
        {{ form.non_field_errors }}            
      </div>
    </div>

    <div class="row text-center">
      <div class="mb-3 col-sm-12 col-lg-6 offset-lg-3">
        {{ form.vaccine_brand.errors }}
        <label for="{{ form.vaccine_brand.id_for_label }}"><strong class="text-white">Vaccine Brand:</strong> </label>
        <select name="vaccine_brand" id="id_vaccine_brand">
          {% for value, text in form.VACCINE_CHOICES %}
            <option value="{{value}}">{{ text }}</option>
          {% endfor %}
        </select>
        <!-- {{ form.vaccine_brand }} -->
      </div>
    </div>

    <div class="row">
      <div class="mb-3 col-sm-12 col-lg-6 offset-lg-3">
          {{ form.lot_num_1.errors }}
          <input type="text" class="form-control" placeholder="First Dose Lot#" name="lot_num_1" required="" id="id_lot_num_1">
      </div>        
    </div>

    <div class="row">
      <div class="mb-3 col-lg-6 col-sm-12 offset-lg-3">
        {{ form.lot_num_2.errors }}
        <input type="text" class="form-control" placeholder="Second Dose Lot# (Not Required)" name="lot_num_2" id="id_lot_num_2">
      </div>        
    </div>

    <div class="row align-items-center">
      <div class="text-center">
        <div
        class="h-captcha"
        data-sitekey="{{ hcaptcha_key }}"
        data-theme="dark"
        data-error-callback="onError"
      ></div>
      </div>
    </div>

    <div class="row align-items-center">
      <div class="mb-3 col-lg-2 col-sm-12 offset-lg-5">
        <input type="submit" class="w-100 btn btn-lg submit-vax-btn" value="Submit">
      </div>
    </div>

  </form>
</section>
<section class="py-5 container">
  <div class="row py-lg-5">
    <div class="col-lg-12 col-md-8 mx-auto">
      <h1 class="fw-light text-center">Disclaimer!</h1>
      <p class="lead text-center">Not suggested for validation outside of the US.</p>
      <p class="lead text-center">As this tool is a labor of love to help combat fake vaccination cards and to spread the knowledge of the flaws in using the vaccination cards as a form of meaningful validation, it is still not perfect. Due to no official affiliation with any pharmaceutical company the data used for validation can not be guaranteed to be 100% accurate. However the Lot Number data is provided from official Johnson and Johnson, and Moderna sites as used by Health Care Practioners to determine the expiration dates based on Lot Numbers. Even so I don't even fully trust these sources for up-to-the-minute data.</p>
    </div>
  </div>
  <div class="row py-lg-5">
    <div class="col-lg-12 col-md-8 mx-auto">
      <h1 class="fw-light text-center">What is this?</h1>
      <p class="lead text-center">This is a web application that can be used to validate the Lot Numbers that are <em>(or should be)</em> located on your COVID-19 Vaccination Record Card.</p>
    </div>
  </div>
  <div class="row py-lg-2">
    <div class="col-lg-12 col-md-8 mx-auto">
      <h1 class="fw-light text-center">How Does This Work?</h1>
      <p class="lead text-center">Break out your nifty COVID-19 Vaccination Record Card then follow these easy steps:</p>
      <ol class="text-center">
        <li>Look for the name of the Vaccine Brand/Manufacturer on your card.</li>
        <li>Click the drop down labeled "Vaccine Brand" and select the name from your card</li>
        <li>Next enter the Lot Numbers into the First Dose and Second Dose fields</li>
        <li>Click the "Submit" button!</li>
      </ol>
    </div>
  </div>
  <div class="row py-lg-2">
    <div class="col-lg-12 col-md-8 mx-auto">
      <h1 class="fw-light text-center">Why?</h1>
      <p class="lead text-center">The COVID-19 Vaccination Record Cards are currently being forged by and/or sold to Anti-vaxxers. <a href="https://www.cbsnews.com/news/covid-vaccination-cards-fake-scammers-fraud/">(Link)</a></p>
      <p class="lead text-center">Some places/people/organizations may rely on these cards as proof that one has been vaccinated and that's truly a big issue. When the CDC created the card their intention was to provide people with something that could help patients keep track of their records and remember their second dose appointment. I want to say it was analog because it was something both the technically inclined and savy could both keep ahold pretty easily. I don't want to believe that the CDC intended for places to use this card as a means of validation for those who got the vaccine and those who didn't.</p>
      <p class="lead text-center">I say that because there is nothing on the piece of paper that helps keep them unique or forgery proof. No embossing or holographs or code that can be used in a system for folks to do any proper validation.</p>
    </div>
  </div>
</section>
{% endblock content %}

validator/vaxvalidator/templates/privacy-policy.html
{% extends "base.html" %}

{% block title %}Vax Card Validator | Disclaimer & Privacy Policy{% endblock title %}

{% block content %}
<section class="py-5 container-fluid">
    <div class="row text-center">
        <div class="col-12">
            <h2>Privacy Policy</h2>
        </div>
    </div>
    <div class="row text-center">
        <div class="col-12">
            <p>This is just meant to be a nifty little tool and a thing to say "Oh yeah I did that because I could". Maybe spark conversations and such too.</p>
            <p>The short of it, I don't care about your data. Your <strong>IP address</strong> will be logged by which is pretty standard. Your data (IP Address) will not be given to a third party.</p>
        </div>
    </div>
    <div class="row text-center">
        <div class="col-12">
            <h2>Disclaimer</h2>
        </div>
    </div>
    <div class="row text-center">
        <div class="col-12">
            <p>I am not affiliated with the CDC, PFizer, Moderna, or J&J.</p>
            <p>This is just meant to be simple tool to potentially validate Lot numbers. I rely on third party services for this data, so the data is only as accurate as what J&J and Moderna provide.</p>
        </div>
    </div>
  
</section>
{% endblock content %}

validator/vaxvalidator/templates/results.html
{% extends "base.html" %}

{% block title %}Vax Card Validator | Results{% endblock title %}

{% block content %}
<section class="py-5 container-fluid">
    <div class="row text-center">
        <div class="col-12">
            <h2>Vaccine: {{vaccine_brand}}</h2>
        </div>
    </div>
    <div class="row text-center">
        <div class="col-12">
            <h2 class="{% if lot_num_1_result %}success-text{% else %}fail-text{% endif %}">Dose 1 Lot#: {{lot_num_1}} {% if lot_num_1_result %}✅{% else %}❌{% endif %}</h2>
        </div>
    </div>
    {% if lot_num_2 %}
    <div class="row text-center">
        <div class="col-12">
            <h2 class="{% if lot_num_2_result %}success-text{% else %}fail-text{% endif %}">Dose 2 Lot#: {{lot_num_2}}{% if lot_num_2_result %}✅{% else %}❌{% endif %}</h2>
        </div>
    </div>
    {% endif %}
  
</section>
{% endblock content %}